### ISSUE TITLE
Aborted download of m3u

### ISSUE THREAD

**Issue by MichelFR** [hooray4me/m3u2strm#4]
I don't know why but its aborthing when downloading my m3u file.
It's like (just a non working example): 
`http://line.testcdn.net/get.php?username=123abc123&password=abc123abc&type=m3u_plus&output=ts`

And I can download the file by using curl or wget.

Those are my logs:

```
Attaching to ustreamgen
ustreamgen  | ...Starting Download...
ustreamgen  | Traceback (most recent call last):
ustreamgen  |   File "main.py", line 27, in <module>
ustreamgen  |     listhandler.parseIPTVLists(funct, providerurl, directory, moviesDestination, tvshowsDestination, eventsDestination)
ustreamgen  |   File "/m3u2strm/listhandler.py", line 9, in parseIPTVLists
ustreamgen  |     downloadAndParseLists(type, url, endrange)
ustreamgen  |   File "/m3u2strm/listhandler.py", line 32, in downloadAndParseLists
ustreamgen  |     downloadAndParseList(url, type)
ustreamgen  |   File "/m3u2strm/listhandler.py", line 39, in downloadAndParseList
ustreamgen  |     print(wget.download(url, ('m3u/' + filename + '.m3u')))
ustreamgen  |   File "/usr/local/lib/python3.8/dist-packages/wget.py", line 526, in download
ustreamgen  |     (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
ustreamgen  |     with contextlib.closing(urlopen(url, data)) as fp:
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
ustreamgen  |     return opener.open(url, data, timeout)
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 531, in open
ustreamgen  |     response = meth(req, response)
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
ustreamgen  |     response = self.parent.error(
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 569, in error
ustreamgen  |     return self._call_chain(*args)
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
ustreamgen  |     result = func(*args)
ustreamgen  |   File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
ustreamgen  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
ustreamgen  | urllib.error.HTTPError: HTTP Error 403: Forbidden
ustreamgen  | no crontab for root
```

**Comment by hooray4me** [comment]
We refactored the code in the containerized environment. I have not pulled that code over to the script only repo here. I'll try to get that done soon
